name: Regression and unitary tests

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.7"
          - os: ubuntu-22.04
            python-version: "3.12"
          - os: macos-14
            python-version: "3.12"
          - os: windows-2019
            python-version: "3.12"

    runs-on: "${{ matrix.os }}"
    
    name: Regression and unitary tests 
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python

    - name: Install dependencies and Project
      run: |
         #conda config --add channels conda-forge
         conda config --set channel_priority strict
         conda install -c conda-forge --file requirements.txt
         conda install scipy
         conda install pip
         
         pip install .
         pip install ase==3.22.1
         echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

    - name: Install Gfortran and Compile Driver
      shell: bash
      run: |
         sudo apt-get update
         sudo apt-get install gfortran
         cd drivers/f90
         make

    - name: unit-tests
      shell: bash
      run: |
         pwd
         i-pi-tests -t unit

    - name: regtests
      shell: bash
      run: |
         pwd
         i-pi-tests -t regtests

