name: Regression and unitary tests

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.7"
          - os: ubuntu-22.04
            python-version: "3.12"
          - os: macos-14
            python-version: "3.12"
          - os: windows-2019
            python-version: "3.12"

    runs-on: "${{ matrix.os }}"
    
    name: Regression and unitary tests 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

    - run: which python

    - name: Install dependencies and Project
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt 
         pip install .
         pip install ase==3.22.1
         echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

    - name: Install Gfortran and Compile Driver
      shell: bash
      run: |
         sudo apt-get update
         sudo apt-get install gfortran
         cd drivers/f90
         make

    - name: unit-tests
      shell: bash
      run: |
         pwd
         i-pi-tests -t unit

    - name: regtests
      shell: bash
      run: |
         pwd
         i-pi-tests -t regtests

